// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://patrgzfblgexmetxmwvu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhdHJnemZibGdleG1ldHhtd3Z1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMDI1MjYsImV4cCI6MjA2NTY3ODUyNn0.2bDYDjZbpd_UH3bdB18085syHze13Ag5ArSGv5C2SDY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);